spring:
  datasource:
    url: jdbc:mysql://47.116.113.174:3306/docker
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: 47.116.113.174
    port: 6379

server:
  port: 8080

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  type-aliases-package: com.docker.entity.**
  configuration:
    map-underscore-to-camel-case: true
